### ISSUE TITLE
ACTIVIDAD 3 Cuadro Comparativo

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-MarcoRg06#1]
Actividad 3 Cuadro comparativo 
Nombre: Marco Uriel Rosas Garcia 1BS
[CUADRO COMPARATIVO_Método científico.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-MarcoRg06/files/9466553/CUADRO.COMPARATIVO_Metodo.cientifico.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 18.3 % del 20%

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
